import { makeStyles } from '@mui/styles';
import { redesignColors } from './authRedesign';
import { onRose, palette, radius, shadow } from './tokens';

export const eventDetailRedesignStyles = makeStyles({
	screen: {
		minHeight: '100vh',
		width: '100%',
		display: 'flex',
		flexDirection: 'column',
		backgroundColor: palette.ground,
		paddingBottom: '160px',
	},
	topBar: {
		display: 'flex',
		alignItems: 'center',
		gap: '14px',
		padding: '16px 20px',
		backgroundColor: palette.white,
	},
	topBarDivider: {
		width: '1px',
		height: '20px',
		backgroundColor: redesignColors.inputBorder,
	},
	topBarTitle: {
		flexGrow: 1,
		'&.MuiTypography-root': {
			textAlign: 'center',
			fontWeight: 700,
			fontSize: '16px',
			color: palette.ink,
			overflow: 'hidden',
			textOverflow: 'ellipsis',
			whiteSpace: 'nowrap',
		},
	},
	content: {
		padding: '20px 20px 0',
		display: 'flex',
		flexDirection: 'column',
		gap: '16px',
	},
	hero: {
		position: 'relative',
		backgroundColor: redesignColors.headerRose,
		borderRadius: radius.sheet,
		padding: '22px',
		color: palette.white,
	},
	heroIcon: {
		width: '48px',
		height: '48px',
		borderRadius: radius.input,
		backgroundColor: onRose.surface,
		display: 'flex',
		alignItems: 'center',
		justifyContent: 'center',
		marginBottom: '18px',
	},
	heroActions: {
		position: 'absolute',
		top: '18px',
		insetInlineEnd: '18px',
		display: 'flex',
		gap: '8px',
	},
	heroEditButton: {
		'&.MuiIconButton-root': {
			width: '40px',
			height: '40px',
			borderRadius: radius.chip,
			backgroundColor: onRose.surface,
			color: palette.white,
		},
	},
	heroDeleteButton: {
		'&.MuiIconButton-root': {
			width: '40px',
			height: '40px',
			borderRadius: radius.chip,
			backgroundColor: 'rgba(220, 53, 69, 0.35)',
			color: palette.white,
		},
	},
	heroTitle: {
		'&.MuiTypography-root': {
			fontWeight: 700,
			fontSize: '22px',
			color: palette.white,
		},
	},
	heroSubtitle: {
		'&.MuiTypography-root': {
			fontSize: '13px',
			color: onRose.medium,
			marginTop: '4px',
		},
	},
	sectionTitle: {
		'&.MuiTypography-root': {
			fontWeight: 700,
			fontSize: '15px',
			color: palette.ink,
		},
	},
	locationCard: {
		backgroundColor: palette.white,
		borderRadius: radius.row,
		padding: '14px 16px',
		display: 'flex',
		alignItems: 'center',
		gap: '14px',
		boxShadow: shadow.card,
	},
	locationIcon: {
		width: '40px',
		height: '40px',
		borderRadius: radius.chip,
		backgroundColor: '#DCEFC9',
		color: '#5C8A2B',
		display: 'flex',
		alignItems: 'center',
		justifyContent: 'center',
		flexShrink: 0,
	},
	locationName: {
		flexGrow: 1,
		'&.MuiTypography-root': {
			fontWeight: 600,
			fontSize: '14px',
			color: palette.ink,
		},
	},
	mapLinkButton: {
		'&.MuiIconButton-root': {
			width: '40px',
			height: '40px',
			borderRadius: radius.chip,
			backgroundColor: palette.subtle,
			color: palette.ink,
			flexShrink: 0,
		},
	},
	statRow: {
		backgroundColor: palette.white,
		borderRadius: radius.row,
		padding: '14px 16px',
		display: 'flex',
		alignItems: 'center',
		gap: '14px',
		boxShadow: shadow.card,
	},
	statRowIcon: {
		width: '40px',
		height: '40px',
		borderRadius: radius.chip,
		display: 'flex',
		alignItems: 'center',
		justifyContent: 'center',
		flexShrink: 0,
	},
	statRowLabel: {
		flexGrow: 1,
		'&.MuiTypography-root': {
			fontWeight: 500,
			fontSize: '14px',
			color: palette.ink,
		},
	},
	statRowValue: {
		backgroundColor: palette.subtle,
		borderRadius: '10px',
		padding: '6px 14px',
		fontWeight: 700,
		fontSize: '14px',
		color: palette.ink,
	},
	qrCard: {
		backgroundColor: palette.white,
		borderRadius: radius.row,
		padding: '20px',
		display: 'flex',
		flexDirection: 'column',
		alignItems: 'center',
		gap: '12px',
		boxShadow: shadow.card,
	},
	qrImage: {
		width: '180px',
		height: '180px',
		borderRadius: radius.chip,
	},
	heroTopRow: {
		display: 'flex',
		alignItems: 'center',
		justifyContent: 'space-between',
		marginBottom: '18px',
	},
	heroDayBadge: {
		width: '40px',
		height: '40px',
		borderRadius: radius.chip,
		backgroundColor: onRose.surface,
		color: palette.white,
		display: 'flex',
		alignItems: 'center',
		justifyContent: 'center',
		fontWeight: 700,
		fontSize: '15px',
		flexShrink: 0,
	},
	descriptionCard: {
		backgroundColor: palette.white,
		borderRadius: radius.row,
		padding: '16px',
		boxShadow: shadow.card,
	},
	descriptionText: {
		'&.MuiTypography-root': {
			fontSize: '14px',
			color: palette.ink,
			lineHeight: 1.6,
		},
	},
	participateButton: {
		'&.MuiButton-root': {
			backgroundColor: redesignColors.successGreen,
			color: palette.white,
			borderRadius: radius.input,
			padding: '14px',
			fontSize: '15px',
			fontWeight: 600,
			textTransform: 'none',
			boxShadow: shadow.none,
			'&:hover': {
				backgroundColor: redesignColors.successGreenHover,
				boxShadow: shadow.none,
			},
			'&.Mui-disabled': {
				backgroundColor: '#D8E5C4',
				color: palette.white,
			},
		},
	},
	participatedBanner: {
		backgroundColor: palette.white,
		borderRadius: radius.input,
		padding: '16px',
		textAlign: 'center',
		'&.MuiTypography-root': {
			color: redesignColors.successGreen,
			fontWeight: 600,
			fontSize: '14px',
		},
	},
});
